name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@v1.0.3
      # "with" dan isinya harus menjorok ke dalam seperti ini
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Pindah ke direktori proyek
          cd /home/pudingtepuni.store/public_html
          
          # Atur agar direktori aman digunakan oleh user root
          git config --global --add safe.directory /home/pudingtepuni.store/public_html
          
          # Ganti 'git pull' dengan dua perintah ini untuk update paksa
          git fetch origin main
          git reset --hard origin/main
          
          echo "🚀 Deployment finished, running Laravel commands..."
          
          # Izinkan Composer dijalankan sebagai root
          export COMPOSER_ALLOW_SUPERUSER=1
          
          # Jalankan perintah-perintah Laravel
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan migrate --force
          php artisan optimize:clear