name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@v1.0.3
      # "with" dan isinya harus menjorok ke dalam seperti ini
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/pudingtepuni.store/public_html
          git config --global --add safe.directory /home/pudingtepuni.store/public_html
          git fetch origin main
          git reset --hard origin/main
          
          echo "🚀 Deployment finished, running Laravel commands..."
          export COMPOSER_ALLOW_SUPERUSER=1
          
          # Hapus folder vendor dan file lock untuk instalasi bersih
          rm -rf vendor composer.lock
          
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan migrate --force
          php artisan optimize:clear